/**
 * Design Pioneer agent interfaces — the specialized agent that establishes
 * the visual quality floor during early build by producing three artifacts:
 *   1. Experience Shell — the app foundation with design system tokens
 *   2. Component Library — project-specific reusable components
 *   3. Anti-Slop Ruleset — project-specific pattern enforcement
 *
 * Spec Section 7.1 — The Design Problem (why the Pioneer exists)
 * Spec Section 7.2 — The Design Pioneer (what it produces)
 * Spec Section 7.3 — Seven-Layer Design Enforcement Stack (Layer 1)
 */

// ---------------------------------------------------------------------------
// Design tokens — the atomic units of the design system
// ---------------------------------------------------------------------------

/**
 * A single design token — a named value in the design system.
 *
 * Tokens are expressed as CSS custom properties so all agents can reference
 * them without hardcoding values. Hardcoded values are caught by the
 * anti-slop linter (Layer 5).
 *
 * Spec Section 7.2, Artifact 1 — "the full color/typography/spacing system"
 * Spec Section 7.2, Artifact 2 — "tokens/ — colors, typography, spacing,
 * shadows, animations, gradients (all as CSS custom properties)"
 */
export interface IDesignToken {
  /** CSS custom property name (e.g., "--color-primary-500"). */
  readonly name: string;
  /** CSS value (e.g., "hsl(220, 90%, 56%)"). */
  readonly value: string;
  /** Token category (e.g., "color", "typography", "spacing"). */
  readonly category: string;
  /** Human-readable description of this token's purpose. */
  readonly description: string;
}

/**
 * The complete design token set — organized by category.
 *
 * All tokens are CSS custom properties. Builder agents reference these
 * instead of hardcoding values. The anti-slop linter's hardcoded-color
 * patterns enforce this at Layers 4-5.
 *
 * Spec Section 7.2, Artifact 2 — tokens/ directory structure.
 */
export interface IDesignTokenSet {
  readonly colors: readonly IDesignToken[];
  readonly typography: readonly IDesignToken[];
  readonly spacing: readonly IDesignToken[];
  readonly shadows: readonly IDesignToken[];
  readonly animations: readonly IDesignToken[];
  readonly gradients: readonly IDesignToken[];
}

// ---------------------------------------------------------------------------
// Generated files — output of the Design Pioneer's code generation
// ---------------------------------------------------------------------------

/**
 * A file generated by the Design Pioneer agent.
 *
 * The Pioneer uses filesystem tools to write these files to the repository.
 * This interface captures the structured output for artifact tracking
 * and dependency graph integration.
 */
export interface IGeneratedFile {
  /** File path relative to repository root. */
  readonly path: string;
  /** File content. */
  readonly content: string;
  /** Why this file exists — used in goal assignment context for builders. */
  readonly purpose: string;
}

// ---------------------------------------------------------------------------
// Artifact 1: Experience Shell
// ---------------------------------------------------------------------------

/**
 * IExperienceShell — the app foundation built by the Design Pioneer.
 *
 * The Experience Shell is the landing page built using design_references
 * dependencies at maximum intensity. It renders on the integration server
 * within the first 5-10 minutes, establishing the visual quality floor
 * that all subsequent builder agents must maintain.
 *
 * Spec Section 7.2, Artifact 1 — "WebGL shader effects on hero elements,
 * GSAP + ScrollTrigger entrance animations, Lenis smooth scrolling,
 * custom cursor behavior, the full color/typography/spacing system,
 * page transitions, skeleton loading states, and responsive behavior."
 *
 * Spec Section 7.3, Layer 1 — "Dedicated agent creates Experience Shell
 * + components" as the visual quality floor.
 */
export interface IExperienceShell {
  /** Files that make up the Experience Shell. */
  readonly files: readonly IGeneratedFile[];
  /** Design tokens embedded in the shell. */
  readonly tokenSet: IDesignTokenSet;
  /** Effect names configured in the shell (e.g., "ShaderHover", "SmoothScroll"). */
  readonly effects: readonly string[];
  /** Layout system description (responsive breakpoints, grid configuration). */
  readonly layoutSystem: string;
  /** Whether the shell includes responsive behavior across breakpoints. */
  readonly responsive: boolean;
  /** When the shell was produced. */
  readonly createdAt: Date;
}

// ---------------------------------------------------------------------------
// Artifact 2: Component Library
// ---------------------------------------------------------------------------

/**
 * An effect template in the component library.
 *
 * Spec Section 7.2, Artifact 2 — "effects/ — ShaderHover, ScrollReveal,
 * SmoothScroll, PageTransition, ParallaxLayer, TextReveal, MagneticButton,
 * GrainOverlay"
 */
export interface IEffectTemplate {
  /** Effect name (e.g., "ShaderHover"). */
  readonly name: string;
  /** File path relative to repo root. */
  readonly path: string;
  /** What this effect does. */
  readonly description: string;
  /** NPM packages this effect requires (e.g., ["three", "gsap"]). */
  readonly dependencies: readonly string[];
}

/**
 * A component template in the component library.
 *
 * Spec Section 7.2, Artifact 2 — "components/ — Button, Card, Input,
 * Modal, Navigation, LoadingSkeleton, Toast (all with non-trivial
 * visual behavior)"
 */
export interface IComponentTemplate {
  /** Component name (e.g., "Button"). */
  readonly name: string;
  /** File path relative to repo root. */
  readonly path: string;
  /** What this component does. */
  readonly description: string;
  /** Non-trivial visual behaviors (e.g., "magnetic hover effect", "ripple animation"). */
  readonly visualBehaviors: readonly string[];
  /** Whether this component includes animation. */
  readonly hasAnimation: boolean;
}

/**
 * A layout template in the component library.
 *
 * Spec Section 7.2, Artifact 2 — "layouts/ — AppShell, AuthLayout,
 * DashboardLayout"
 */
export interface ILayoutTemplate {
  /** Layout name (e.g., "AppShell"). */
  readonly name: string;
  /** File path relative to repo root. */
  readonly path: string;
  /** What this layout provides. */
  readonly description: string;
  /** Responsive breakpoints this layout handles. */
  readonly breakpoints: readonly string[];
}

/**
 * An example implementation in the component library.
 *
 * Spec Section 7.2, Artifact 2 — "examples/ — hero-section,
 * feature-grid, testimonials, cta-section (complete, working
 * reference implementations)"
 */
export interface IExampleTemplate {
  /** Example name (e.g., "hero-section"). */
  readonly name: string;
  /** File path relative to repo root. */
  readonly path: string;
  /** What this example demonstrates. */
  readonly description: string;
  /** Components used in this example. */
  readonly componentsUsed: readonly string[];
  /** Effects used in this example. */
  readonly effectsUsed: readonly string[];
}

/**
 * IComponentLibrary — the project-specific component library.
 *
 * A comprehensive /src/design-system/ directory with tokens, effects,
 * components, layouts, and examples. Builder agents import from this
 * library instead of writing generic patterns.
 *
 * Spec Section 7.2, Artifact 2 — complete directory structure.
 * Spec Section 7.3, Layer 2 — "Positive context: goal assignment
 * includes component references" so agents know the library exists.
 */
export interface IComponentLibrary {
  /** Base path for the design system (e.g., "src/design-system"). */
  readonly basePath: string;
  /** Design tokens organized by category. */
  readonly tokens: IDesignTokenSet;
  /** Visual effect components. */
  readonly effects: readonly IEffectTemplate[];
  /** UI components with non-trivial visual behavior. */
  readonly components: readonly IComponentTemplate[];
  /** Page layout templates. */
  readonly layouts: readonly ILayoutTemplate[];
  /** Working reference implementations. */
  readonly examples: readonly IExampleTemplate[];
  /** All generated files in the component library. */
  readonly files: readonly IGeneratedFile[];
}

// ---------------------------------------------------------------------------
// Artifact 3: Anti-Slop Ruleset
// ---------------------------------------------------------------------------

/**
 * A required pattern — the inverse of a banned pattern.
 *
 * While ISlopPattern detects things that MUST NOT exist, required patterns
 * detect things that MUST exist. The absence of a required pattern is a
 * violation.
 *
 * Spec Section 7.2, Artifact 3 — "required patterns (SmoothScroll,
 * PageTransition, ScrollReveal on every page; hover/focus/active states
 * on every interactive element)"
 */
export interface IRequiredPattern {
  /** Unique identifier. */
  readonly id: string;
  /** What must be present. */
  readonly description: string;
  /** Regex to detect presence of the required pattern. */
  readonly pattern: string;
  /** Where this pattern must appear (e.g., "every page component", "every interactive element"). */
  readonly scope: string;
  /** What to add when the pattern is missing. */
  readonly suggestion: string;
  /** File globs to check for this pattern. Empty = all files. */
  readonly applicableGlobs: readonly string[];
}

/**
 * A quality threshold — numeric minimum for a design quality metric.
 *
 * Spec Section 7.2, Artifact 3 — "quality thresholds (minimum animations
 * per page, shader effect presence, skeleton loading coverage)"
 *
 * Spec Section 7.3, Layer 7 — "Design quality scoring (scored):
 * Quantitative score with user-adjustable threshold"
 */
export interface IQualityThreshold {
  /** Unique identifier. */
  readonly id: string;
  /** What this threshold measures (e.g., "animations-per-page"). */
  readonly metric: string;
  /** Minimum acceptable value. */
  readonly minimumValue: number;
  /** What this metric means and why it matters. */
  readonly description: string;
  /** Unit of measurement (e.g., "count", "percentage", "score"). */
  readonly unit: string;
}

/**
 * IAntiSlopRuleset — project-specific anti-slop rules produced by
 * the Design Pioneer.
 *
 * Extends the default slop patterns from slop-patterns.ts (Step 11)
 * with project-specific banned patterns, required patterns, and
 * quality thresholds derived from the design brief and component library.
 *
 * Spec Section 7.2, Artifact 3 — "machine-readable specification of
 * banned patterns, required patterns, and quality thresholds."
 *
 * Spec Section 7.3, Layer 5 — banned patterns integrated into merge gate.
 */
export interface IAntiSlopRuleset {
  /** Project-specific banned patterns (extend the defaults from Step 11). */
  readonly bannedPatterns: readonly import("./slop.js").ISlopPattern[];
  /** Required patterns — things that MUST be present. */
  readonly requiredPatterns: readonly IRequiredPattern[];
  /** Quality thresholds — numeric minimums for design quality metrics. */
  readonly qualityThresholds: readonly IQualityThreshold[];
  /** Whether this ruleset extends (true) or replaces (false) the default patterns. */
  readonly extendsDefaults: boolean;
  /** Project name this ruleset was generated for. */
  readonly projectName: string;
  /** When this ruleset was generated. */
  readonly createdAt: Date;
}

// ---------------------------------------------------------------------------
// Aggregated artifacts
// ---------------------------------------------------------------------------

/**
 * IDesignPioneerArtifacts — the complete output of the Design Pioneer's
 * early-build work.
 *
 * Contains all three artifacts plus metadata. The orchestrator uses this
 * to update the dependency graph (unblocking UI goals), inject component
 * references into builder goal assignments (Layer 2), and configure the
 * anti-slop linter with project-specific patterns.
 *
 * Spec Section 7.2 — all three artifacts described.
 * Spec Section 7.3, Layers 1-2 — Pioneer output feeds downstream enforcement.
 */
export interface IDesignPioneerArtifacts {
  /** Artifact 1: The Experience Shell. */
  readonly shell: IExperienceShell;
  /** Artifact 2: The Component Library. */
  readonly componentLibrary: IComponentLibrary;
  /** Artifact 3: The Anti-Slop Ruleset. */
  readonly antiSlopRuleset: IAntiSlopRuleset;
  /** All files generated across all three artifacts. */
  readonly allGeneratedFiles: readonly IGeneratedFile[];
  /** The build this was produced for. */
  readonly buildId: string;
  /** When artifacts were produced. */
  readonly producedAt: Date;
}

// ---------------------------------------------------------------------------
// Design Pioneer agent configuration and interface
// ---------------------------------------------------------------------------

/**
 * Configuration for the Design Pioneer agent.
 *
 * Spec Section 7.2 — "The Pioneer receives enhanced design instruction
 * unique among all agents — explicit instruction to OVERUSE the
 * design_references dependencies, the competitive design reference from
 * ICE Stage 2, and a quality target of 'Awwwards Site of the Day level.'"
 */
export interface IDesignPioneerConfig {
  /** The build this pioneer works on. */
  readonly buildId: string;
  /** The live agent session (design-pioneer role). */
  readonly session: import("./agents.js").ILiveAgentSession;
  /** Design brief from ICE Stage 2 (competitive intelligence). */
  readonly designBrief: import("./ice.js").IDesignBrief;
  /** Living specification from ICE. */
  readonly livingSpec: import("./ice.js").ILivingSpecification;
  /** Absolute path to the repository root. */
  readonly repoPath: string;
  /** Base path for the design system (default: "src/design-system"). */
  readonly designSystemBasePath?: string;
  /** Content of design_references.md (the ONE agent that gets the full file). */
  readonly designReferencesContent?: string;
}

/**
 * IDesignPioneerAgent — the specialized agent that establishes the visual
 * quality floor during early build.
 *
 * The Design Pioneer runs as a high-priority early task. Tasks that don't
 * depend on design system components launch simultaneously. Tasks that
 * WILL produce UI wait until the Pioneer's component library merges.
 * The dependency graph handles this naturally.
 *
 * Spec Section 7.2 — "The Design Pioneer is a specialized Opus 4.6 agent
 * that runs as a high-priority early task."
 * Spec Section 7.3, Layer 1 — "Design Pioneer: Sets visual quality floor."
 */
export interface IDesignPioneerAgent {
  /**
   * Produce all three artifacts.
   *
   * Sends structured prompts to the agent session directing it to:
   * 1. Analyze the design brief and living specification
   * 2. Create the Experience Shell (landing page + design tokens)
   * 3. Build the Component Library (tokens, effects, components, layouts, examples)
   * 4. Generate the Anti-Slop Ruleset (project-specific patterns)
   *
   * Returns the aggregated artifacts. The orchestrator then:
   * - Merges the generated files via the merge gate
   * - Configures the anti-slop linter with project-specific patterns
   * - Updates goal assignments with component library references (Layer 2)
   */
  produce(config: IDesignPioneerConfig): Promise<IDesignPioneerArtifacts>;
}
