/**
 * prism-plan.ts — Planning phase types for Prism engine.
 *
 * Plans are generated by Claude Opus 4.6 from natural language prompts.
 * Every element caption must be SELF-CONTAINED (Invariant 2).
 * Backend contracts are generated DURING planning, BEFORE code gen (Invariant 4).
 */

import type { UIElementType, TextContentSpec, Interaction, NodeVisualSpec } from './prism-graph.js';
import type { BackendContract, DataModelPlan } from './prism-backend.js';
export type { BackendContract, DataModelPlan } from './prism-backend.js';

export interface AppIntent {
  description: string;
  appType: AppType;
  platform: 'web' | 'mobile-web' | 'desktop';
  features: FeatureSpec[];
  visualStyle: VisualStyleSpec;
  integrations: IntegrationSpec[];
  contentStrategy: 'static' | 'dynamic' | 'real-time';
  commercialClassification: 'personal' | 'commercial' | 'enterprise';
  confidenceScore: number;
  ambiguities: string[];
  reasoning: string;
}

export type AppType =
  | 'landing-page' | 'saas-dashboard' | 'e-commerce' | 'portfolio'
  | 'blog' | 'social-platform' | 'marketplace' | 'crm'
  | 'project-management' | 'analytics-dashboard' | 'ai-tool'
  | 'video-platform' | 'messaging-app' | 'booking-system'
  | 'documentation' | 'admin-panel' | 'custom';

export interface FeatureSpec {
  name: string;
  description: string;
  priority: 'must-have' | 'should-have' | 'nice-to-have';
  category: 'frontend' | 'backend' | 'integration' | 'infrastructure';
  inferredFrom: 'user-input' | 'competitive-analysis' | 'domain-knowledge' | 'security';
  acceptanceCriteria: string[];
}

export interface VisualStyleSpec {
  colorScheme: 'light' | 'dark' | 'auto';
  primaryColor: string;
  accentColor: string;
  typography: {
    headingFont: string;
    bodyFont: string;
    monoFont: string;
  };
  designLanguage: 'minimal' | 'glassmorphism' | 'neobrutalism' | 'material'
    | 'corporate' | 'playful' | 'editorial' | 'custom';
  referenceUrls: string[];
  extractedTokens: ExtractedDesignTokens | null;
}

export interface ExtractedDesignTokens {
  source: string;
  colors: Record<string, string>;
  fonts: string[];
  spacing: Record<string, string>;
  borderRadius: Record<string, string>;
}

export interface IntegrationSpec {
  serviceId: string;
  purpose: string;
  requiredScopes: string[];
  credentialStatus: 'connected' | 'pending' | 'missing';
}

export interface PrismPlan {
  id: string;
  projectId: string;
  prompt: string;
  intent: AppIntent;
  competitiveAnalysis: CompetitiveAnalysis | null;
  inferredNeeds: InferredNeed[];
  graph: PrismGraphPlan;
  backendContract: BackendContract;
  estimatedCost: number;
  estimatedTimeSeconds: number;
  status: 'pending' | 'approved' | 'generating' | 'complete' | 'failed';
}

export interface PrismGraphPlan {
  hubs: HubPlan[];
  sharedComponents: SharedComponentPlan[];
  dataModels: DataModelPlan[];
  services: ServicePlan[];
  navigationGraph: NavigationEdge[];
}

export interface HubPlan {
  id: string;
  name: string;
  route: string;
  description: string;
  layoutTemplate: string;
  authRequired: boolean;
  elements: ElementPlan[];
}

export interface ElementPlan {
  id: string;
  type: UIElementType;
  caption: string;
  position: { x: number; y: number; width: number; height: number };
  textContent: TextContentSpec[];
  interactions: Interaction[];
  isShared: boolean;
}

export interface SharedComponentPlan {
  id: string;
  name: string;
  type: UIElementType;
  caption: string;
  hubIds: string[];
  overridesPerHub: Record<string, Partial<NodeVisualSpec>>;
}

export interface CompetitiveAnalysis {
  competitors: CompetitorEntry[];
  designInsights: string[];
  featureGaps: string[];
  analyzedAt: string;
}

export interface CompetitorEntry {
  url: string;
  name: string;
  screenshots: string[];
  features: string[];
  designTokens: ExtractedDesignTokens | null;
}

export interface InferredNeed {
  name: string;
  description: string;
  source: 'competitive-analysis' | 'domain-knowledge' | 'security' | 'ux-best-practice';
  priority: 'must-have' | 'should-have' | 'nice-to-have';
  features: FeatureSpec[];
}

export interface ServicePlan {
  id: string;
  name: string;
  type: 'database' | 'auth' | 'storage' | 'email' | 'payment' | 'analytics' | 'search' | 'custom';
  provider: string;
  configuration: Record<string, unknown>;
}

export interface NavigationEdge {
  sourceHubId: string;
  targetHubId: string;
  trigger: string;
  conditions?: Record<string, unknown>;
}
