/**
 * deployment.ts — Deploy generated backend to user-selected target platforms.
 *
 * Spec reference: Section 14 — Deployment Targets
 *
 * Supported targets:
 *   | Target                | Deploy Time | Method                    |
 *   | cloudflare-workers    | ~3s         | Wrangler API              |
 *   | aws-lambda            | ~5s         | Pulumi Automation API     |
 *   | vercel-functions      | ~10s        | Vercel SDK                |
 *   | fly-machines          | <1s         | Machines REST API         |
 *   | supabase              | ~5s         | Management API            |
 *   | modal                 | ~2s         | Function deployment       |
 *
 * INVARIANT 6: Modal Executes, Vercel Routes. Actual heavy deployment work
 * runs on Modal. This module provides the TypeScript interfaces and dispatch
 * logic; the Python backend_worker.py has the deployment config templates.
 */

import type { BackendTarget } from '../types.js';

export interface DeploymentConfig {
  target: BackendTarget;
  configContent: string;
  appName: string;
  region?: string;
}

export interface DeploymentResult {
  target: BackendTarget;
  success: boolean;
  url?: string;
  error?: string;
  deployTimeMs: number;
}

export interface DeploymentManifest {
  deployments: DeploymentResult[];
  deployedAt: string;
  totalTimeMs: number;
}

/**
 * Build deployment configurations for all selected targets.
 *
 * The actual config content is generated by the Python backend_worker.py
 * on Modal. This function structures the deployment request.
 */
export function buildDeploymentRequest(
  targets: BackendTarget[],
  deploymentConfigs: Record<string, string>,
  appName: string,
): DeploymentConfig[] {
  return targets
    .filter(target => deploymentConfigs[target])
    .map(target => ({
      target,
      configContent: deploymentConfigs[target],
      appName,
    }));
}

/**
 * Validate that a deployment target is supported and has required configuration.
 */
export function validateDeploymentTarget(
  target: BackendTarget,
  credentials: Record<string, string>,
): { valid: boolean; missingCredentials: string[] } {
  const required = TARGET_CREDENTIALS[target] ?? [];
  const missing = required.filter(key => !credentials[key]);

  return {
    valid: missing.length === 0,
    missingCredentials: missing,
  };
}

/**
 * Build a deployment manifest from deployment results.
 * Stored in prism_graphs.backendManifest.
 */
export function buildDeploymentManifest(
  results: DeploymentResult[],
): DeploymentManifest {
  const totalTimeMs = results.reduce((sum, r) => sum + r.deployTimeMs, 0);

  return {
    deployments: results,
    deployedAt: new Date().toISOString(),
    totalTimeMs,
  };
}

/**
 * Get the expected deployment time range for a target.
 */
export function getExpectedDeployTime(target: BackendTarget): {
  minMs: number;
  maxMs: number;
} {
  const times: Record<BackendTarget, { minMs: number; maxMs: number }> = {
    'cloudflare-workers': { minMs: 2000, maxMs: 5000 },
    'aws-lambda': { minMs: 3000, maxMs: 10000 },
    'vercel-functions': { minMs: 5000, maxMs: 15000 },
    'fly-machines': { minMs: 500, maxMs: 2000 },
    'modal': { minMs: 1000, maxMs: 3000 },
    'supabase': { minMs: 3000, maxMs: 8000 },
    'runpod': { minMs: 2000, maxMs: 5000 },
  };

  return times[target] ?? { minMs: 5000, maxMs: 15000 };
}

// ---------------------------------------------------------------------------
// Credential requirements per target
// ---------------------------------------------------------------------------

const TARGET_CREDENTIALS: Record<BackendTarget, string[]> = {
  'cloudflare-workers': ['CLOUDFLARE_API_TOKEN', 'CLOUDFLARE_ACCOUNT_ID'],
  'aws-lambda': ['AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY', 'AWS_REGION'],
  'vercel-functions': ['VERCEL_TOKEN'],
  'fly-machines': ['FLY_API_TOKEN'],
  'modal': ['MODAL_TOKEN_ID', 'MODAL_TOKEN_SECRET'],
  'supabase': ['SUPABASE_ACCESS_TOKEN', 'SUPABASE_PROJECT_REF'],
  'runpod': ['RUNPOD_API_KEY'],
};
