import nodemailer from 'nodemailer';

// SMTP transport — configure via environment variables
// Supports any SMTP provider (SendGrid, AWS SES, Resend, Mailgun, etc.)
const transporter = nodemailer.createTransport({
  host: process.env.SMTP_HOST || 'smtp.sendgrid.net',
  port: parseInt(process.env.SMTP_PORT || '587', 10),
  secure: process.env.SMTP_SECURE === 'true',
  auth: {
    user: process.env.SMTP_USER || 'apikey',
    pass: process.env.SMTP_PASS || '',
  },
});

const FROM_EMAIL = process.env.FROM_EMAIL || 'noreply@kriptik.app';
const FROM_NAME = process.env.FROM_NAME || 'KripTik AI';

/**
 * Send a password reset email with a secure token link.
 * The URL is generated by Better Auth and contains a signed token.
 */
export async function sendPasswordResetEmail(to: string, resetUrl: string): Promise<void> {
  if (!process.env.SMTP_PASS) {
    console.error('[Email] SMTP_PASS not configured — cannot send password reset email');
    console.log('[Email] Would have sent reset link to:', to);
    console.log('[Email] Reset URL:', resetUrl);
    throw new Error('Email service not configured. Contact support for password reset.');
  }

  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="margin:0;padding:0;background-color:#f5f0eb;font-family:'Segoe UI',Tahoma,Geneva,Verdana,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f5f0eb;padding:40px 20px;">
    <tr>
      <td align="center">
        <table width="480" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:16px;box-shadow:0 4px 24px rgba(0,0,0,0.08);overflow:hidden;">
          <!-- Header -->
          <tr>
            <td style="padding:32px 32px 16px;text-align:center;">
              <h1 style="margin:0;font-size:24px;font-weight:700;color:#1a1a1a;letter-spacing:-0.5px;">
                KripTik AI
              </h1>
            </td>
          </tr>
          <!-- Content -->
          <tr>
            <td style="padding:16px 32px 24px;">
              <h2 style="margin:0 0 12px;font-size:20px;font-weight:600;color:#1a1a1a;">
                Reset Your Password
              </h2>
              <p style="margin:0 0 24px;font-size:15px;line-height:1.6;color:#4a4a4a;">
                We received a request to reset your password. Click the button below to create a new password. This link expires in 1 hour.
              </p>
              <table width="100%" cellpadding="0" cellspacing="0">
                <tr>
                  <td align="center">
                    <a href="${resetUrl}" style="display:inline-block;padding:14px 32px;background-color:#1a1a1a;color:#ffffff;text-decoration:none;font-size:15px;font-weight:600;border-radius:10px;box-shadow:0 2px 8px rgba(0,0,0,0.15);">
                      Reset Password
                    </a>
                  </td>
                </tr>
              </table>
              <p style="margin:24px 0 0;font-size:13px;line-height:1.5;color:#8a8a8a;">
                If you didn't request this, you can safely ignore this email. Your password won't be changed.
              </p>
            </td>
          </tr>
          <!-- Footer -->
          <tr>
            <td style="padding:16px 32px 24px;border-top:1px solid #f0ebe5;">
              <p style="margin:0;font-size:12px;color:#8a8a8a;text-align:center;">
                &copy; ${new Date().getFullYear()} KripTik AI &mdash; Build anything with AI
              </p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>`;

  await transporter.sendMail({
    from: `"${FROM_NAME}" <${FROM_EMAIL}>`,
    to,
    subject: 'Reset your KripTik AI password',
    html,
    text: `Reset your password: ${resetUrl}\n\nThis link expires in 1 hour. If you didn't request this, ignore this email.`,
  });

  console.log(`[Email] Password reset email sent to: ${to}`);
}
