/**
 * Create PR Modal
 *
 * Modal for creating Pull Requests after agent work is approved.
 * Integrates with GitHub/GitLab/Bitbucket via pr-integration service.
 *
 * B3: Create PR Modal from integration analysis
 */

import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
    GitBranchIcon,
    CloseIcon,
    CheckIcon,
    Loader2Icon,
    ImagePlusIcon,
    UserIcon,
    AlertCircleIcon,
    CheckCircle2Icon,
    ChevronDownIcon,
    FileCodeIcon,
    TagIcon
} from '../ui/icons';
import { cn } from '@/lib/utils';

// Dark glass styling
const darkGlassPanel = {
    background: 'linear-gradient(145deg, rgba(20,20,25,0.98) 0%, rgba(12,12,16,0.99) 100%)',
    backdropFilter: 'blur(40px) saturate(180%)',
    boxShadow: `
        0 30px 80px rgba(0,0,0,0.5),
        0 15px 40px rgba(0,0,0,0.4),
        inset 0 1px 0 rgba(255,255,255,0.05),
        0 0 0 1px rgba(255,255,255,0.05)
    `,
};

const accentColor = '#c8ff64';

interface Agent {
    id: string;
    name: string;
    taskPrompt?: string;
    verificationScore?: number;
    verificationPassed?: boolean;
    filesChanged?: number;
}

interface CreatePRModalProps {
    isOpen: boolean;
    onClose: () => void;
    projectId: string;
    projectName: string;
    agent?: Agent | null;
    branchName?: string;
    targetBranch?: string;
    filesChanged?: string[];
    verificationResults?: {
        passed: boolean;
        score: number;
        checks: { name: string; passed: boolean }[];
    };
}

export function CreatePRModal({
    isOpen,
    onClose,
    projectId,
    projectName,
    agent,
    branchName = 'kriptik/feature-update',
    targetBranch = 'main',
    filesChanged = [],
    verificationResults
}: CreatePRModalProps) {
    const [prTitle, setPrTitle] = useState('');
    const [prDescription, setPrDescription] = useState('');
    const [addScreenshots, _setAddScreenshots] = useState(true);
    const [requestReview, setRequestReview] = useState(false);
    const [selectedReviewers, setSelectedReviewers] = useState<string[]>([]);
    const [addLabels, setAddLabels] = useState(true);
    const [selectedLabels, setSelectedLabels] = useState<string[]>(['feature', 'ai-generated']);
    const [autoMerge, setAutoMerge] = useState(false);
    const [creating, setCreating] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const [showReviewerDropdown, setShowReviewerDropdown] = useState(false);

    const availableReviewers = ['team-lead', 'senior-dev', 'qa-team'];
    const availableLabels = ['feature', 'bug', 'enhancement', 'ai-generated', 'needs-review', 'urgent'];

    // Generate default title and description
    useEffect(() => {
        if (agent?.taskPrompt) {
            const taskSummary = agent.taskPrompt.length > 50
                ? agent.taskPrompt.substring(0, 50) + '...'
                : agent.taskPrompt;
            setPrTitle(`feat: ${taskSummary}`);
            generateDescription();
        } else {
            setPrTitle(`feat: Updates from ${projectName}`);
            generateDescription();
        }
    }, [agent, projectName]);

    const generateDescription = () => {
        let desc = `## Summary

This PR contains changes generated by KripTik AI Developer Mode.

`;

        if (agent?.taskPrompt) {
            desc += `### Task Description
${agent.taskPrompt}

`;
        }

        desc += `### Changes
${filesChanged.length > 0
    ? filesChanged.map(f => `- \`${f}\``).join('\n')
    : '- Various file updates'
}

`;

        if (verificationResults) {
            desc += `### Verification Results
${verificationResults.passed ? '✅ All checks passed' : '⚠️ Some checks failed'}
- Score: ${verificationResults.score}/100

| Check | Status |
|-------|--------|
${verificationResults.checks.map(c => `| ${c.name} | ${c.passed ? '✅' : '❌'} |`).join('\n')}

`;
        }

        desc += `---
*Generated by [KripTik AI](https://kriptik.ai) Developer Mode*`;

        setPrDescription(desc);
    };

    const handleCreate = async () => {
        if (!prTitle.trim()) {
            setError('Please provide a PR title');
            return;
        }

        setCreating(true);
        setError(null);

        try {
            const response = await fetch('/api/developer-mode/pr/create', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                credentials: 'include',
                body: JSON.stringify({
                    projectId,
                    agentId: agent?.id,
                    title: prTitle,
                    description: prDescription,
                    branchName,
                    targetBranch,
                    options: {
                        addScreenshots,
                        reviewers: requestReview ? selectedReviewers : [],
                        labels: addLabels ? selectedLabels : [],
                        autoMerge,
                    }
                })
            });

            const data = await response.json();

            if (data.success) {
                // Open PR in new tab
                if (data.prUrl) {
                    window.open(data.prUrl, '_blank');
                }
                onClose();
            } else {
                setError(data.error || 'Failed to create PR');
            }
        } catch (err) {
            console.error('Failed to create PR:', err);
            setError('Failed to create PR. Check your GitHub connection.');
        }

        setCreating(false);
    };

    const handleMergeDirectly = async () => {
        if (!confirm('Are you sure you want to merge directly to main? This bypasses PR review.')) {
            return;
        }

        setCreating(true);
        setError(null);

        try {
            const response = await fetch('/api/developer-mode/pr/merge-direct', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                credentials: 'include',
                body: JSON.stringify({
                    projectId,
                    branchName,
                    targetBranch,
                    message: prTitle
                })
            });

            const data = await response.json();

            if (data.success) {
                onClose();
            } else {
                setError(data.error || 'Failed to merge');
            }
        } catch (err) {
            setError('Failed to merge directly');
        }

        setCreating(false);
    };

    if (!isOpen) return null;

    return (
        <AnimatePresence>
            <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm"
                onClick={onClose}
            >
                <motion.div
                    initial={{ scale: 0.95, opacity: 0, y: 20 }}
                    animate={{ scale: 1, opacity: 1, y: 0 }}
                    exit={{ scale: 0.95, opacity: 0, y: 20 }}
                    transition={{ type: 'spring', damping: 25, stiffness: 300 }}
                    onClick={(e) => e.stopPropagation()}
                    className="w-full max-w-2xl max-h-[90vh] overflow-hidden rounded-2xl"
                    style={darkGlassPanel}
                >
                    {/* Header */}
                    <div className="flex items-center justify-between p-6 border-b border-white/5">
                        <div className="flex items-center gap-3">
                            <div
                                className="p-2 rounded-xl"
                                style={{ background: `${accentColor}20` }}
                            >
                                <GitBranchIcon size={20} style={{ color: accentColor }} />
                            </div>
                            <div>
                                <h2 className="text-lg font-semibold text-white">Create Pull Request</h2>
                                <p className="text-xs text-white/40">
                                    {branchName} → {targetBranch}
                                </p>
                            </div>
                        </div>
                        <button
                            onClick={onClose}
                            className="p-2 rounded-lg hover:bg-white/5 transition-colors"
                        >
                            <CloseIcon size={20} className="text-white/40" />
                        </button>
                    </div>

                    {/* Content - Scrollable */}
                    <div className="p-6 overflow-auto max-h-[60vh] space-y-6">
                        {/* Agent Info */}
                        {agent && (
                            <div className="flex items-center justify-between p-4 bg-white/[0.02] rounded-xl border border-white/10">
                                <div>
                                    <span className="text-sm text-white/60">Agent</span>
                                    <p className="text-white font-medium">{agent.name}</p>
                                </div>
                                <div className="flex items-center gap-3">
                                    {agent.verificationPassed !== undefined && (
                                        <span className={cn(
                                            'text-xs px-2 py-1 rounded-full',
                                            agent.verificationPassed
                                                ? 'bg-emerald-500/20 text-emerald-400'
                                                : 'bg-amber-500/20 text-amber-400'
                                        )}>
                                            {agent.verificationPassed ? '✓ Verified' : 'Pending Review'}
                                        </span>
                                    )}
                                    {agent.filesChanged !== undefined && (
                                        <span className="text-xs text-white/40 flex items-center gap-1">
                                            <FileCodeIcon size={12} />
                                            {agent.filesChanged} files
                                        </span>
                                    )}
                                </div>
                            </div>
                        )}

                        {/* Verification Summary */}
                        {verificationResults && (
                            <div className={cn(
                                'p-4 rounded-xl border',
                                verificationResults.passed
                                    ? 'bg-emerald-500/5 border-emerald-500/20'
                                    : 'bg-amber-500/5 border-amber-500/20'
                            )}>
                                <div className="flex items-center gap-2 mb-2">
                                    {verificationResults.passed ? (
                                        <CheckCircle2Icon size={16} className="text-emerald-400" />
                                    ) : (
                                        <AlertCircleIcon size={16} className="text-amber-400" />
                                    )}
                                    <span className={cn(
                                        'text-sm font-medium',
                                        verificationResults.passed ? 'text-emerald-400' : 'text-amber-400'
                                    )}>
                                        Verification: {verificationResults.score}/100
                                    </span>
                                </div>
                                <div className="flex flex-wrap gap-2">
                                    {verificationResults.checks.map((check, idx) => (
                                        <span
                                            key={idx}
                                            className={cn(
                                                'text-xs px-2 py-1 rounded',
                                                check.passed
                                                    ? 'bg-emerald-500/10 text-emerald-400'
                                                    : 'bg-red-500/10 text-red-400'
                                            )}
                                        >
                                            {check.passed ? '✓' : '✗'} {check.name}
                                        </span>
                                    ))}
                                </div>
                            </div>
                        )}

                        {/* Error */}
                        {error && (
                            <div className="flex items-center gap-2 p-3 rounded-lg bg-red-500/10 border border-red-500/20">
                                <AlertCircleIcon size={16} className="text-red-400" />
                                <span className="text-sm text-red-400">{error}</span>
                            </div>
                        )}

                        {/* PR Title */}
                        <div className="space-y-2">
                            <label className="text-sm font-medium text-white/80">PR Title</label>
                            <input
                                type="text"
                                value={prTitle}
                                onChange={(e) => setPrTitle(e.target.value)}
                                placeholder="feat: Add new feature"
                                className="w-full px-4 py-3 rounded-xl bg-white/[0.02] border border-white/10 focus:border-white/20 outline-none text-white placeholder-white/30"
                            />
                        </div>

                        {/* PR Description */}
                        <div className="space-y-2">
                            <label className="text-sm font-medium text-white/80">Description</label>
                            <textarea
                                value={prDescription}
                                onChange={(e) => setPrDescription(e.target.value)}
                                className="w-full h-40 px-4 py-3 rounded-xl bg-white/[0.02] border border-white/10 focus:border-white/20 outline-none text-sm text-white/80 placeholder-white/30 resize-none font-mono"
                            />
                        </div>

                        {/* Options */}
                        <div className="space-y-4">
                            <h4 className="text-sm font-medium text-white/80">Options</h4>

                            {/* Add Screenshots */}
                            <label className="flex items-center gap-3 cursor-pointer">
                                <div
                                    className={cn(
                                        'w-5 h-5 rounded border-2 flex items-center justify-center transition-colors',
                                        addScreenshots
                                            ? 'border-transparent'
                                            : 'border-white/30'
                                    )}
                                    style={addScreenshots ? { background: accentColor } : {}}
                                >
                                    {addScreenshots && <CheckIcon size={12} className="text-black" />}
                                </div>
                                <div className="flex items-center gap-2">
                                    <ImagePlusIcon size={16} className="text-white/40" />
                                    <span className="text-sm text-white/80">Add screenshots (before/after)</span>
                                </div>
                            </label>

                            {/* Request Review */}
                            <div className="space-y-2">
                                <label className="flex items-center gap-3 cursor-pointer">
                                    <div
                                        className={cn(
                                            'w-5 h-5 rounded border-2 flex items-center justify-center transition-colors',
                                            requestReview
                                                ? 'border-transparent'
                                                : 'border-white/30'
                                        )}
                                        style={requestReview ? { background: accentColor } : {}}
                                        onClick={() => setRequestReview(!requestReview)}
                                    >
                                        {requestReview && <CheckIcon size={12} className="text-black" />}
                                    </div>
                                    <div className="flex items-center gap-2">
                                        <UserIcon size={16} className="text-white/40" />
                                        <span className="text-sm text-white/80">Request review from</span>
                                    </div>
                                </label>

                                {requestReview && (
                                    <div className="ml-8 relative">
                                        <button
                                            onClick={() => setShowReviewerDropdown(!showReviewerDropdown)}
                                            className="w-full flex items-center justify-between px-3 py-2 rounded-lg bg-white/[0.02] border border-white/10 text-sm"
                                        >
                                            <span className="text-white/60">
                                                {selectedReviewers.length > 0
                                                    ? selectedReviewers.join(', ')
                                                    : 'Select reviewers...'}
                                            </span>
                                            <ChevronDownIcon size={16} className="text-white/40" />
                                        </button>
                                        {showReviewerDropdown && (
                                            <div className="absolute top-full left-0 right-0 mt-1 py-1 rounded-lg bg-slate-800 border border-white/10 z-10">
                                                {availableReviewers.map(reviewer => (
                                                    <button
                                                        key={reviewer}
                                                        onClick={() => {
                                                            setSelectedReviewers(prev =>
                                                                prev.includes(reviewer)
                                                                    ? prev.filter(r => r !== reviewer)
                                                                    : [...prev, reviewer]
                                                            );
                                                        }}
                                                        className="w-full flex items-center gap-2 px-3 py-2 text-sm text-white/70 hover:bg-white/5"
                                                    >
                                                        <div className={cn(
                                                            'w-4 h-4 rounded border flex items-center justify-center',
                                                            selectedReviewers.includes(reviewer)
                                                                ? 'bg-cyan-500 border-cyan-500'
                                                                : 'border-white/30'
                                                        )}>
                                                            {selectedReviewers.includes(reviewer) && (
                                                                <CheckIcon size={12} className="text-black" />
                                                            )}
                                                        </div>
                                                        {reviewer}
                                                    </button>
                                                ))}
                                            </div>
                                        )}
                                    </div>
                                )}
                            </div>

                            {/* Labels */}
                            <div className="space-y-2">
                                <label className="flex items-center gap-3 cursor-pointer">
                                    <div
                                        className={cn(
                                            'w-5 h-5 rounded border-2 flex items-center justify-center transition-colors',
                                            addLabels
                                                ? 'border-transparent'
                                                : 'border-white/30'
                                        )}
                                        style={addLabels ? { background: accentColor } : {}}
                                        onClick={() => setAddLabels(!addLabels)}
                                    >
                                        {addLabels && <CheckIcon size={12} className="text-black" />}
                                    </div>
                                    <div className="flex items-center gap-2">
                                        <TagIcon size={16} className="text-white/40" />
                                        <span className="text-sm text-white/80">Add labels</span>
                                    </div>
                                </label>

                                {addLabels && (
                                    <div className="ml-8 flex flex-wrap gap-2">
                                        {availableLabels.map(label => (
                                            <button
                                                key={label}
                                                onClick={() => {
                                                    setSelectedLabels(prev =>
                                                        prev.includes(label)
                                                            ? prev.filter(l => l !== label)
                                                            : [...prev, label]
                                                    );
                                                }}
                                                className={cn(
                                                    'px-2 py-1 rounded-full text-xs font-medium transition-colors border',
                                                    selectedLabels.includes(label)
                                                        ? 'text-black border-transparent'
                                                        : 'text-white/60 border-white/20 hover:border-white/40'
                                                )}
                                                style={selectedLabels.includes(label) ? {
                                                    background: accentColor
                                                } : {}}
                                            >
                                                {label}
                                            </button>
                                        ))}
                                    </div>
                                )}
                            </div>

                            {/* Auto-merge */}
                            <label className="flex items-center gap-3 cursor-pointer">
                                <div
                                    className={cn(
                                        'w-5 h-5 rounded border-2 flex items-center justify-center transition-colors',
                                        autoMerge
                                            ? 'border-transparent'
                                            : 'border-white/30'
                                    )}
                                    style={autoMerge ? { background: accentColor } : {}}
                                    onClick={() => setAutoMerge(!autoMerge)}
                                >
                                    {autoMerge && <CheckIcon size={12} className="text-black" />}
                                </div>
                                <div className="flex items-center gap-2">
                                    <GitBranchIcon size={16} className="text-white/40" />
                                    <span className="text-sm text-white/80">Auto-merge when checks pass</span>
                                </div>
                            </label>
                        </div>
                    </div>

                    {/* Footer */}
                    <div className="flex items-center justify-between p-6 border-t border-white/5">
                        <button
                            onClick={handleMergeDirectly}
                            disabled={creating}
                            className="px-4 py-2 rounded-lg text-sm text-amber-400 hover:text-amber-300 hover:bg-amber-500/10 transition-all"
                        >
                            Merge Directly to Main
                        </button>
                        <div className="flex items-center gap-3">
                            <button
                                onClick={onClose}
                                className="px-4 py-2 rounded-lg text-sm text-white/60 hover:text-white/80 hover:bg-white/5 transition-all"
                            >
                                Cancel
                            </button>
                            <button
                                onClick={handleCreate}
                                disabled={creating || !prTitle.trim()}
                                className="flex items-center gap-2 px-6 py-2 rounded-lg font-medium transition-all disabled:opacity-50"
                                style={{
                                    background: `linear-gradient(145deg, ${accentColor} 0%, ${accentColor}cc 100%)`,
                                    color: '#000',
                                }}
                            >
                                {creating ? (
                                    <Loader2Icon size={16} className="animate-spin" />
                                ) : (
                                    <GitBranchIcon size={16} />
                                )}
                                Create PR
                            </button>
                        </div>
                    </div>
                </motion.div>
            </motion.div>
        </AnimatePresence>
    );
}

export default CreatePRModal;

